apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-go-app
  template:
    metadata:
      labels:
        app: sample-go-app
    spec:
      containers:
      - name: sample-go-app
        image: icn.ocir.io/orasejapan/ochacafe5-3:arm
---
apiVersion: v1
kind: Service
metadata:
  name: sample-go-app-service
spec:
  type: ClusterIP
  ports:
  - name: sample-go-app-service
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: sample-go-app
